### Advance operation with Business example 

In [3]:
import numpy as np
import matplotlib.pyplot as pit

In [9]:
#Data structure :[restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],   #A
    [2, 120000, 140000, 160000, 190000],   #B
    [3, 200000, 230000, 260000, 300000],   #C
    [4, 180000, 210000, 240000, 270000],   #D
    [5, 160000, 185000, 205000, 230000],   #E
])

print("\n sales data shape ", sales_data.shape)

print("\n sample data for 2nd restau: \n", sales_data[1])   #write index no. to print perticular row
print("\n sample data for 1st 3 restau: \n", sales_data[0:3])
print("\n sample data for 1st 3 restau: \n", sales_data[:3]) # this 2 are same but different method to represent
print("\n sample data: \n", sales_data[:,1:]) # before comma ":" means all the rows will be print 
# (a,b) here a= rows and b= column
 # (1: ) here 1 means it will start with index 1 in column and after colon nothing is mension so include all column after index no. 1 





 sales data shape  (5, 5)

 sample data for 2nd restau: 
 [     2 120000 140000 160000 190000]

 sample data for 1st 3 restau: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 sample data for 1st 3 restau: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 sample data: 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [ ]:
# total sales per year  

print(np.)

