Phase-1 and basic

In [7]:
import numpy as np

### creating array from list

In [16]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


List vs numpy array

In [17]:
py_list = [1,2,3,4]
print("python list multiplication ", py_list * 2)

np_array = np.array([1,2,3,4])   #element wise multiplication
print("python array multiplication ", np_array * 2)




python list multiplication  [1, 2, 3, 4, 1, 2, 3, 4]
python array multiplication  [2 4 6 8]


In [18]:
import time

start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n list operation time: ", time.time()- start)

start = time.time()
np_array = np.arange(10000000) *2
print("\n numpy operation time: ", time.time()- start)


 list operation time:  0.4468421936035156

 numpy operation time:  0.034293174743652344


creating array from scratch

In [ ]:
zeros = np.zeros((3,3))
print("zeros array :\n", zeros)

ones = np.ones((2,4))
print("ones array :\n", ones)


full = np.full((2,2), 7)
print("full array :\n", full)

random = np.random.random((4,3)) * 100
print("random array :\n", random) 

sequence = np.arange(0, 10, 2)   # 10 will not inclusive 
print("sequence array :\n", sequence) 

zeros array :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array :
 [[7 7]
 [7 7]]
random array :
 [[36.7461037  47.50894299 45.41662322]
 [14.42860282 61.56178378 26.2284604 ]
 [54.63186637 61.63609471 25.02526648]
 [51.52654517 67.01046653 61.51554432]]
sequence array :
 [0 2 4 6 8]


### vector, Matrix and tensor

In [26]:
vector = np.array([1,2,3])
print("vector: ", vector)

matrix  = np.array([[1,2,3],
                    [4,5,6]])
print("matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4],
                    [5,6],[7,8]]])
print("tensor: \n", tensor)

vector:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr =np.array([[1,2,3],
               [4,5,]])
print("Shape ",arr.shape)   # gives no. of   rows and column
print("Dimension ",arr.ndim) #gives dimension( 1d, 2d, etc)
print("Size ",arr.size)    # gives total element of the array
print("data types ",arr.dtype) # gives data types

Shape  (2, 3)
Dimension  2
Size  6
data types  int64


### Array Reshaping

In [37]:
arr = np.arange(12)
print("Original array ", arr)

Reshaped = arr.reshape((3,4))
print("Reshaped array \n", Reshaped)

flattened = Reshaped.flatten()
print("flattened array \n", flattened)

# revel return view, insteado of copy
raveled = Reshaped.ravel()
print("reveled array \n", raveled)

#Transpose
transpose = Reshaped.T
print("Transpose array \n", transpose)





Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
