## Numpy Array Operation

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic Slicing ", arr[2:7])
print("with step ", arr[1:8:2])
print("negative indexing ",arr[-3])

basic Slicing  [3 4 5 6 7]
with step  [2 4 6 8]
negative indexing  7


In [3]:
         #  column  0 1 2     row
arr_2d = np.array([[1,2,3],  # 0
                   [5,6,7],  # 1
                   [4,8,9]])  # 2
print("specific element" ,arr_2d[2,1])     # this is allow in numpy not in python

print("Entire row: ", arr_2d[1])   #row x column
print("Entire column: ", arr_2d[:,1])   #row x column


specific element 8
Entire row:  [5 6 7]
Entire column:  [2 6 8]


Sorting

In [4]:
unsorted = np.array([3,6,4,9,1,5,0,2])
print("Sorted Array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,4],[2,6],[1,5]])
print("sorted 2d array by column: \n",np.sort(arr_2d_unsorted , axis=0))
print("sorted 2d array by row: \n",np.sort(arr_2d_unsorted , axis=1))


Sorted Array:  [0 1 2 3 4 5 6 9]
sorted 2d array by column: 
 [[1 4]
 [2 5]
 [3 6]]
sorted 2d array by row: 
 [[3 4]
 [2 6]
 [1 5]]


## Filter

In [5]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_no = number[number%2 ==0]
print("even number ", even_no)

even number  [ 2  4  6  8 10]


### Filter with mask

In [6]:
mask = number > 5
print("Numbers greater than 5: ",number[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [ ]:
indices = [0, 2,4,9]   #index number
print(number[indices])

where_result = np.where(number>5)
print(where_result)                    # here index number will print
print("np where", number[where_result]) 

[ 1  3  5 10]
(array([5, 6, 7, 8, 9]),)
np where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(number>5 , number*4 , number*2)  # (condition, True, False)
# if(number > 5 ):
#     print(number *4)
# else:
#     print(number)
print("condition_array ", condition_array)

condition_array  [ 2  4  6  8 10 24 28 32 36 40]


### Adding and removing data

In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility 

In [ ]:
a= np.array([1,2,3])     # it check where the shape of the array is same or not  
b= np.array([4,5,6])
c= np.array([7,8,9,10])

print("compatiblity shapes: ", a.shape == b.shape)
print("compatiblity shapes: ", c.shape == b.shape)

compatiblity shapes:  True
compatiblity shapes:  False


### Adding new Row and column in the array

In [32]:
original = np.array([[1,2,3],[4,5,6]])

add_row = np.array([7,8,9])
new_array_row = np.vstack((original, add_row))   # vstack --> vertical stack means 
print("New array row: \n", new_array_row)

add_column = np.array([[7],[8]])
new_array_column = np.hstack((original,add_column))   # vstack --> vertical stack means 
print("New array column: \n", new_array_column)

New array row: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
New array column: 
 [[1 2 3 7]
 [4 5 6 8]]


### deleting new Row and column in the array

In [50]:
array = np.array([1,2,3,4,5,6,7,8])
deleted_element = np.delete(array, 5)
print("deleted array ",deleted_element)

array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
delete =np.delete(array_2d, 1,1)
print("deleted array \n",delete)


deleted array  [1 2 3 4 5 7 8]
deleted array 
 [[1 3]
 [4 6]
 [7 9]]
